// Copyright Matt Smith - 2021

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

public class Question2
{
    public static void main(String[] args)
    {
    	int prev = 0;
    	int cur  = 1;
    	int sum  = 0;
    	int temp = 0;

 		while (cur < 4000000)
 		{
 			if (cur % 2 == 0)
 				sum += cur;

 			temp = cur;
 			cur += prev;
 			prev = temp;
 		}

 		System.out.print("The sum of the even Fibonacci numbers less than 4000000 is: ");
 		System.out.println(sum);
 	}
}